version: '3.8'

services:
  auth:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    image: 1161/auth:latest  # Set the desired image name here
    ports:
      - "1161:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
